# deploy a single Nginx container pod with 3 replicas exposed on port 80
# in this example we are not specifying the latest version of the nginx pod
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1       # At most, 1 pod can be unavailable during the update.
      maxSurge: 2             # Up to 2 extra pods can be created during the update.
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
