# this manifest creates a pod with a single Nginx container and exposes the pod on port 80
apiVersion: v1
kind: Pod
metadata:
  name: single-container-pod
  labels:
    purpose: demonstrate-single-container
spec:
  containers:
  - name: example-container
    image: nginx:latest
    ports:
    - containerPort: 80
